### PR TITLE
Release?

### PR DESCRIPTION
**Pull request by manulera**
Hi @BjornFJohansson, I think with all recent bug fixes and improvements to the documentation, we should do a release to pypi.

It does not have to be a major release, I think, since it's mostly bug fixes and docs, and there are no breaking changes as far as I remember. Let me know what you think.

### CODE REVIEW

**Comment by manulera** [comment]
Hey @BjornFJohansson any thoughts on this?

**Review by BjornFJohansson — APPROVED** [review]
I think this is fine. There are of course lots of changes, but all tests passes.

**Comment by manulera** [comment]
Ok then! Merge it is!

**Comment by manulera** [comment]
By the way @BjornFJohansson what is the process you follow to release to pypi? If I want to release a next version (say 5.3.0), how do I do so?

**Pull request merged**
