### PR TITLE
fix icon link + 2 small bug fixes

### PR DESCRIPTION
**Pull request by manulera**

### CODE REVIEW

**Comment by manulera** [comment]
Hi @BjornFJohansson this is a small fix of the icon link. Because it's to the master branch it requires your approval

**Comment by manulera** [comment]
I added two small fixes:

#324
#325

**Comment by BjornFJohansson** [comment]
Do we merge?

**Comment by manulera** [comment]
@BjornFJohansson can you make a pre-release for pypi?

**Pull request merged**
